[package]
name = "team_point_estimator"
version = "0.1.0"
authors = ["Elliott Rezny <erezny@gmail.com>"]

[dependencies]
"actix-web" = "0.7.8"
"actix" = "0.7.4"
"serde" = "*"
"serde_json" = "*"
"serde_derive" = "*"